manifest = "183478ba9247f22515bdaf35b37447c6225d8cf229a2a60122bf068a226b5479"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
target = "//:static_assert"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
target = "//:type_traits"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.47.0" ]
revision = "f6585b1993077d3de95ebcf766e3346b8aebb490"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.47.0" ]
revision = "f39e5671b0d09010441b6549031deb68b7c75d44"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.47.0" ]
revision = "b17cd5bfcc8eb6cde44203dde758b9776586a75a"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.47.0" ]
revision = "52f57f55eac32e2e80f4d21d1886af41f3b150b7"
