targets = ["//:smart_ptr"]

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
version = "1.20.2"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
version = "1.20.2"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
version = "1.20.2"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
version = "1.20.2"