targets = [ "//:smart-ptr" ]

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-core"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-assert"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-move"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-predef"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-align"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-throw_exception"
version = "branch=master"
