manifest = "ba0e9476726c8514f6f00005fb1821d56fe0011d040a16e906bb9f6c7d55bece"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
target = "//:static_assert"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
target = "//:type_traits"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.23.0" ]
revision = "70a7f134f7a2ca18b0a3dcdf62356ba7f0b33441"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.23.0" ]
revision = "6f32ccf3df54d8fb4a95f0be0cc838af677fac3d"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.23.0" ]
revision = "72127b50dde3e51fb64d0c6a61c94131cfd48ef4"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.23.0" ]
revision = "d1b428093c830816aab337795fce8dc4d4fc9fa7"
