manifest = "954c50ca1ea5f0bceda97d500d04c8b007c45842616fcb79d3f5f9deebf7c0b2"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[[dependency]]
package = "github.com/buckaroo-pm/boost-move"
target = "//:move"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
target = "//:static_assert"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
target = "//:type_traits"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.50.0" ]
revision = "0af936e42c3db7c0f8a63e21265a645b70abb9cb"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.50.0" ]
revision = "279b99e09f2d86b2ccd97d2c6ebd37a9f6003c94"

[lock."github.com/buckaroo-pm/boost-move"]
versions = [ "1.50.0" ]
revision = "7c8870de2f28e66cd84ba79fc3cb2ba47e45dd5b"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.50.0" ]
revision = "8d094e1cc2572bbe09ed6d3fc370a4fe4141939d"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.50.0" ]
revision = "af76a5aef78b01d8e4b520133233a12fd69fe304"
