manifest = "1ca685d817d2ab329d969d8f31b5d3c946fd4a674b446a9dd07bf8da345e4dab"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[[dependency]]
package = "github.com/buckaroo-pm/boost-move"
target = "//:move"

[[dependency]]
package = "github.com/buckaroo-pm/boost-predef"
target = "//:predef"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
target = "//:static_assert"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
target = "//:type_traits"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.55.0" ]
revision = "892598f066f15a4b8352bbd6b5f2b1a90e12e6fc"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.55.0" ]
revision = "8fe65abe2334e0d84c2cba4c768ec2f2360b33e1"

[lock."github.com/buckaroo-pm/boost-move"]
versions = [ "1.55.0" ]
revision = "76fa046db20cda9182689feb8b6397363851de45"

[lock."github.com/buckaroo-pm/boost-predef"]
versions = [ "1.55.0" ]
revision = "92a9de7baf8132f059e13977fcb6302e0c1a0e0c"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.55.0" ]
revision = "e14d6eb7ed4f944d0c0bb723e4732c5ea80d0d1d"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.55.0" ]
revision = "e53e7e72e660990dcc5c6c015d724fab0c4516a6"
