targets = ["//:smart-ptr"]

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
version = "1.68.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-core"
version = "1.68.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-assert"
version = "1.68.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
version = "1.68.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-move"
version = "1.68.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-predef"
version = "1.68.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
version = "1.68.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-align"
version = "1.68.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
version = "1.68.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-throw_exception"
version = "1.68.0"