manifest = "bcbb6cdc4302038f47f9bff91f126bc68d699684812c59800b3a6200d5bc6547"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[[dependency]]
package = "github.com/buckaroo-pm/boost-move"
target = "//:move"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
target = "//:static_assert"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
target = "//:type_traits"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.54.0" ]
revision = "110b58c9fdc5502003d1fbd5270cd6bcc8a1a09b"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.54.0" ]
revision = "d2f3338b08866620bbf261d40ff2cf53ffc956a3"

[lock."github.com/buckaroo-pm/boost-move"]
versions = [ "1.54.0" ]
revision = "fc33676d8b3c9b75dcc7b7acf692471c3ad98cc1"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.54.0" ]
revision = "6252ee7fc574cd013c1ac1adb368b3948af184a7"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.54.0" ]
revision = "05bbb54685b47675ba8aa61232fada6dc08959f8"
