targets = ["//:smart-ptr"]

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
version = "1.48.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
version = "1.48.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-move"
version = "1.48.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
version = "1.48.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
version = "1.48.0"